[package]
name = "mekzqza/one-short-arena"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"